### PR TITLE
Add information to `HealthCertificate_ValidityState_ExpiringSoon_description` what to do if the certificate is not the currently used one

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR adds more information on what to do if the certificate about to expire is not the currently used certificate to `HealthCertificate_ValidityState_ExpiringSoon_description`.

## Link to Jira
Related to GitHub issue https://github.com/corona-warn-app/cwa-documentation/issues/889 which was not mirrored to JIRA.

## Screenshots

| Light mode | Dark mode |
|---|---|
| Light | Dark |

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Please note that an expired certificate will show "Bitte erneuern Sie das Zertifikat" without the hint to only do so if this is the currently used one. Is this how it is intended? In general the behavior in this is open to improvements (e.g. add a logic so that the text to renew certificates is only shown if the certificate about to expire / expired is the one currently used.

**Comment by KathrinLuecke** [comment]
@Ein-Tim We already plan to adjust the text for expired certificates to make it clear that only currently used certificates need to be renewed. A corresponding Jira-Ticket is in progress.
Regarding your suggestion for the text about soon expiring certificates, it doesn't harm to add it I think, but actually the first sentence already says it that you only have to take action if this is your currently used certificate. So it's a bit redundant... What do you think @mlenkeit ?

**Comment by Ein-Tim** [comment]
@KathrinLuecke I had a conversation with a user on Twitter (https://twitter.com/cyberpunk1410/status/1526434922805829633?s=21&t=zVsz6cONCPq8fU3clFrO4g) reg. this, it seems like at least currently the behaviour is confusing. So I went ahead and added this sentence. But for sure it's up to you!

Thanks for letting me know that you plan improvements here!

**Review by CV113 — APPROVED** [review]
UA approved

**Comment by Ein-Tim** [comment]
Further feedback from Twitter: https://twitter.com/mikedeeeeeee/status/1527186021149986818?s=21&t=5ZyLNMDh7-BsnKm1DUcu0A

I think the sentence should be added. It doesn't harm anyone and makes it 100% clear to the user what to do.

**Comment by Ein-Tim** [comment]
@marcussc could you please approve the workflows to run? Thanks!

**Comment by KathrinLuecke** [comment]
Hi @Ein-Tim ,
I created https://github.com/corona-warn-app/cwa-app-ios/pull/4563
https://github.com/corona-warn-app/cwa-app-android/pull/5212
to take over this change, as your external PR could not be merged.
Best,
Kathrin

**Comment by Ein-Tim** [comment]
Thanks @KathrinLuecke!

**Pull request closed without merging**
