### PR TITLE
Change "Remove Certificate of Recovery" to "Delete Certificate of Recovery" and "Remove Test Certificate" to "Delete Certificate of Recovery" (COMMUNITY)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR changes "Remove Certificate of Recovery" to "Delete Certificate of Recovery" and "Remove Test Certificate" to "Delete Certificate of Recovery".

## Link to Jira
Internal Tracking ID: [EXPOSUREAPP-10462](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10462)

## Screenshots
Sadly I can't import any certificates into the Emulator.

---
Internal Tracking ID: [EXPOSUREAPP-10462](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10462)

### CODE REVIEW

**Comment by dsarkar** [comment]
Good morning @Ein-Tim! Thanks. Internal Tracking ID: [EXPOSUREAPP-10462](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10462)

**Comment by KathrinLuecke** [comment]
@CV113 You are about to change everything from "remove" to "delete", right? So this means, "Delete Vaccination Certificate" should stay, but "Remove Certificate of Recovery" & "Remove Test Certificate" should be changed.

**Comment by Ein-Tim** [comment]
@KathrinLuecke 

Do you want me to change it the other way around? "Remove" -> "Delete"?

**Comment by KathrinLuecke** [comment]
@Ein-Tim Yes, it was decided that we will use delete (löschen) instead of remove (entfernen) everywhere.

**Comment by Ein-Tim** [comment]
@KathrinLuecke 

Okay, I will change this PR accordingly.

**Comment by Ein-Tim** [comment]
@KathrinLuecke I changed the PR! Please take another look.

CC @CV113

**Comment by KathrinLuecke** [comment]
@Ein-Tim Thank you! We will change this in German and then it will also be changed in the translation languages.

**Comment by Ein-Tim** [comment]
@KathrinLuecke

Okay, I thought so.

Then I will close this PR and wait for the translation PR.
Is this planned for `release/2.14.x` or `release/2.15.x`?

**Comment by KathrinLuecke** [comment]
It is planned for 2.14.

**Pull request closed without merging**
