### PR TITLE
Make it clearer to only scan your certificates (COMMUNITY)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR improves the "UniversalQRScanner_InstructionDescription" to make it clearer that one should not use the CWA to scan the certificates from others (to verify them).

## Link to Jira
- GitHub Issue: https://github.com/corona-warn-app/cwa-wishlist/issues/666
	- [EXPOSUREAPP-10263](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10263)

This PR is only a quick "improvement attempt" for https://github.com/corona-warn-app/cwa-wishlist/issues/666, there has to be done more on this to solve the issue. 
Users are thinking they can use the universal QR code scanner to verify the certificates from others. Best would be if there would be another paragraph added which states that for verifying the certificate the CovPassCheck-App has to be used. 
However, as no such change is in sight, I decided to provide this little PR. 

## Screenshots

| Light Mode | Dark Mode |
|---|---|
|   |   |

---
Internal Tracking ID: [EXPOSUREAPP-10408](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10408)

### CODE REVIEW

**Comment by KathrinLuecke** [comment]
Thank you @Ein-Tim for this suggestion.
What about: Ihre PCR-Tests, Schnelltests, Testzertifikate, Impfzertifikate, Genesenenzertifikate sowie Check-ins
Because I think you should as well only scan you own PCR-Tests or Schnelltests.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10408](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10408)

**Review by CV113 — APPROVED** [review]
UA approved

**Comment by Ein-Tim** [comment]
@KathrinLuecke 

Agreed, you're right. I'll change this as soon as possible.

**Comment by jucktnich** [comment]
There should be something like "und ihrer Familienangehörigen"

**Comment by Ein-Tim** [comment]
@KathrinLuecke 

I implemented your suggestion in [`6bf6f55` (#3793)](https://github.com/corona-warn-app/cwa-app-ios/pull/3793/commits/6bf6f550d931c2682f73047ad9629aee3a8e98f9).

Let me know whether I should add what @jucktnich proposed. (-:

**Review by naveeddotio — APPROVED** [review]

**Pull request merged**
