### PR TITLE
Fix double "die" (COMMUNITY)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR fixes the "Statistics_Info_FullyVaccinated_Text", there was one "die" too much.

For more information see https://github.com/corona-warn-app/cwa-documentation/issues/669

## Link to Jira
n/a

## Screenshots

| Before | Afterwards |
|---|---|
|  |  |

### CODE REVIEW

**Comment by hija** [comment]
Looks good to me 😊

**Review by NataliaLemmerth — APPROVED** [review]
UA approved

**Review by marcussc — APPROVED** [review]

**Review by nickguendling — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Thanks for the merge! Why can't this go into `release/2.6.x`? 
Android has fixed this in version 2.6 (see https://github.com/corona-warn-app/cwa-documentation/issues/669#issuecomment-886154458)

**Comment by marcussc** [comment]
@Ein-Tim Not sure about Android, but for iOS the time to make changes to 2.6 that are not release blocking has passed :)

**Pull request merged**
