### PR TITLE
Translation Delivery

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Review by Ein-Tim — CHANGES_REQUESTED** [review]
In line 119 in the English file, there are two dots at the end of the sentence. 
See #4058 & #4035. This should be fixed. 

Cc @marcussc

**Comment by marcussc** [comment]
@Ein-Tim Thanks for pointing it out I will check back with translation team :)

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Review by marcussc — APPROVED** [review]

**Review by naveeddotio — APPROVED** [review]

**Pull request merged**
