### PR TITLE
Translation Delivery

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I534472

**Review by steins-code — APPROVED** [review]

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I534472

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I534472

**Review by haosap — APPROVED** [review]

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I534472

**Pull request merged**
