### PR TITLE
Translation Delivery

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @I534472

**Comment by kaddaSz** [comment]
@corona-warn-app/cwa-app-ios-members: **IMPORTANT**: do not merge this yet, until we have clarified the needed translations for 1.3.1

**Review by steins-code — APPROVED** [review]

**Review by kaddaSz — CHANGES_REQUESTED** [review]
PLEASE DO NOT MERGE YET.. We need to clarify the translations for 1.3.1 first. I will let you now, if you can merge.

**Review by kaddaSz — APPROVED** [review]

**Comment by kaddaSz** [comment]
OBSOLETE

**Pull request closed without merging**
