### PR TITLE
[Feature] ENAButton accessibility

### PR DESCRIPTION
**Pull request by eisvogel**
This PR adds full dynamic type support for the ENAButton component.

The changes incorporates commits from this #439. Due to major changes since the initial PR was opened it is easier to apply the changes in individually in separate PRs, rather than trying to resolve all conflicts.

This PR includes:
* Removal of `ENACloneButton`
* Proper resizing of `ENAButton` when changing dynamic type, including proper handling of the submission flow buttons

### CODE REVIEW

**Comment by AdnanZiSAP** [comment]
The code looks good. Let me run some tests...

**Comment by AdnanZiSAP** [comment]
Tested. Look good everywhere except the Risk details screen:

IMG_29C72F963645-1

**Review by AdnanZiSAP — CHANGES_REQUESTED** [review]
Risk details _Update_ button is not resizing properly.

**Comment by AdnanZiSAP** [comment]
> Risk details _Update_ button is not resizing properly.

Fixed with [this commit](https://github.com/corona-warn-app/cwa-app-ios/pull/752/commits/428787eecb3c39262baa6a6851534cfb155a0d7f).

**Review by AdnanZiSAP — APPROVED** [review]

**Review by haosap — APPROVED** [review]

**Pull request merged**
