### PR TITLE
Decapitalize "IHR BEFUND" (COMMUNITY)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR decapitalises [the text](https://user-images.githubusercontent.com/67682506/118121235-723ca780-b3f1-11eb-9cd6-af990be74fbc.PNG) "IHR BEFUND" inside of the PCR "Ihr Testergebnis" box with a pending test result to be consistent with [the text](https://user-images.githubusercontent.com/67682506/118121230-710b7a80-b3f1-11eb-9291-3b50a264da7d.PNG) inside of the RAT "Ihr Testergebnis" box with a pending test result.

## Link to Jira
non (yet)

## Screenshots
Not possible here because I can't enter a PCR test into the app on the emulator.

### CODE REVIEW

**Review by naveeddotio — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@NataliaLemmerth Could you take a look at my tiny PR, please?

Thank you!

**Review by NataliaLemmerth — APPROVED** [review]
UA approved

**Review by InkenTownsend — APPROVED** [review]
Looks good to me

**Comment by InkenTownsend** [comment]
@Ein-Tim Thank you again for your valuable contribution!

**Pull request merged**
