### PR TITLE
[Feature] Privacy Protection Screen

### PR DESCRIPTION
**Pull request by eisvogel**
This PR implements the Privacy Protection Screen to align with the latest design specifications.

IMG_0026
IMG_0027

### CODE REVIEW

**Review by i336616 — APPROVED** [review]
Perfect, the blank screen looked like a bug :)

**Comment by tens0rfl0w** [comment]
Closes #191 
(Looks good!)

**Comment by EisvogelSAP** [comment]
Yeah, sorry for not using the blurred style. I really liked it, but we were overruled by the design team. :-D

**Comment by tens0rfl0w** [comment]
> Yeah, sorry for not using the blurred style. I really liked it, but we were overruled by the design team. :-D

Sure, no problem! 😄 
I also like that approach, looks really clean! Good for an health app!👍🏽 :)

**Review by steins-code — APPROVED** [review]

**Pull request merged**
