### PR TITLE
fix/5624 enable link preview for onboarding

### PR DESCRIPTION
**Pull request by ndegendogo**
## Description

This PR starts to address an issue that was reported as #2179. The app has a very inconsistent behaviour with regard to links. Several links support a preview behaviour if you press the link long, but several links don't support this. 
The desired behaviour is to support the preview.

The PR adds preview behaviour for the "link to app informations in easy language and sign language" from the first page of the Onboarding flow, and thus aligns the behaviour of this link to the "About the App" page, where the same link is referenced (here the preview behaviour is already implemented).

~Analysis shows that two concurring mechanisms were implemented to open the URL from the Onboarding page.
(1) the link was implemented as an AttributedString in a TextView. In this case iOS opens the link. This mechanism supports the preview.
(2) at the same time, the view controller was setup as delegate for the TextView, and the view controller was extended to open the link with LinkHelper. This mechanism overrides the first mechanism, but it does not support the preview.~

~The solution removes the second mechanism (delegate and extension).
**Note:** Unfortunately this solution will have a negative impact on the robustness of the unit tests.
The LinkHelper mechanism mocks the URL access for UITesting configuration and thus decouples the execution of the unit tests from the true network.
The AttributedString mechanism, however, does not have this mocking.
I am not sure how to resolve this dilemma.
One option would be to bring back the extension, but to setup the delegate only for UITesting (although that solution would be a bit intransparent and needs to be commented well).~

**Edit:** I found an alternate and much better solution. The textview delegate takes now care of the default interaction (open the link with LinkHelper), but allows iOS to perform the alternate actions (like the action menu or the preview).
For unit tests opening the link as well as preview is mocked.

## Link to Jira

Jira: Internal Tracking ID: [EXPOSUREAPP-5624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5624)

github: #2179

## Screenshots

https://user-images.githubusercontent.com/6118267/141700658-97ad290d-fe09-4959-b418-0afcccb507d3.mp4

---
 Internal Tracking ID: [EXPOSUREAPP-5624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5624)

### CODE REVIEW

**Comment by dsarkar** [comment]
@ndegendogo Thanks. Forwarded to Internal Tracking ID: EXPOSUREAPP-5624

**Comment by ndegendogo** [comment]
I have another idea.
I am going to try if I can move this logic into LinkHelper.

***Stay tuned ...***

**Review by marcussc — APPROVED** [review]
Looks better and more general then the old PR 👍

**Comment by ndegendogo** [comment]
@marcussc full ack 😁
I hope I can later use this solution as kind of 'blueprint' to improve handling for all the other external links in the system (some don't yet support preview, some don't yet support the mocking)

**Review by naveeddotio — APPROVED** [review]

**Pull request merged**
