### PR TITLE
Make it clearer that one can't verify certificates from others with the CWA (COMMUNITY)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR makes it clearer that one can verify the certificates you own with the CWA, but not the ones from others.

## Link to Jira
n/a

## Screenshots

---
Internal Tracking ID: [EXPOSUREAPP-10264](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10264)

### CODE REVIEW

**Comment by jucktnich** [comment]
Maybe capitalise "Ihre"?

**Review by CV113 — APPROVED** [review]
UA Approved

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10264](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10264)

**Review by naveeddotio — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@jucktnich 

I think "ihre" is right here, or @CV113?

**Comment by jucktnich** [comment]
@Ein-Tim I think "Ihre" is more polite then "ihre", but I'm no German pro. I could ask my German teacher 😅

**Comment by CV113** [comment]
The sentence begins with "Sie" that means that we are talking to a person that we don't know, we have to be polite ... "ihre" in lower case means her(s) or their(s) and "Ihr" menas you. So "ihr" with capital letter is correct :-)

**Comment by Ein-Tim** [comment]
@jucktnich @CV113 

Thank you! If I have any questions on German language, I'll come back to you 😉

**Comment by CV113** [comment]
@Ein-Tim Sure! Anytime :-P

**Pull request merged**
