### PR TITLE
Fix/6989 wrong number while calling

### PR DESCRIPTION
**Pull request by naveeddotio**
## Description
Wrong number was called due to extra string

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6989

## Screenshots
NA

### CODE REVIEW

**Review by freshking — APPROVED** [review]

**Comment by naveeddotio** [comment]
@NataliaLemmerth @ChristinaTsigganos Can I have your tick here on priority basis?

**Review by NataliaLemmerth — APPROVED** [review]
UA approved

**Review by marcussc — CHANGES_REQUESTED** [review]
We have to wait for the Translation delivery.
Then check and maybe replace this string in the translations as well.

**Comment by naveeddotio** [comment]
> We have to wait for the Translation delivery.
> Then check and maybe replace this string in the translations as well.

That's the confusing part, it's a separate key.

**Comment by marcussc** [comment]
> > We have to wait for the Translation delivery.
> > Then check and maybe replace this string in the translations as well.
> 
> That's the confusing part, it's a separate key. Please recheck.

@naveeddotio Yes, but it is contained in the other translation relevant files as well:
Screenshot 2021-05-10 at 11 18 58
So changing it now would screw the translation process, so we should wait for the incoming translation delivery and then change it in all languages.

**Comment by naveeddotio** [comment]
> > > We have to wait for the Translation delivery.
> > > Then check and maybe replace this string in the translations as well.
> > 
> > 
> > That's the confusing part, it's a separate key. Please recheck.
> 
> @naveeddotio Yes, but it is contained in the other translation relevant files as well:
> Screenshot 2021-05-10 at 11 18 58
> So changing it now would screw the translation process, so we should wait for the incoming translation delivery and then change it in all languages.

Same goes here then!
Screenshot 2021-05-10 at 14 23 09

**Review by marcussc — APPROVED** [review]

**Pull request merged**
