### PR TITLE
Adjustment of iOS text

### PR DESCRIPTION
**Pull request by CV113**
iOS and Android should use the same text.

--> https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11513

### CODE REVIEW

**Review by naveeddotio — APPROVED** [review]

**Review by marcussc — APPROVED** [review]

**Comment by Ein-Tim** [comment]
This reverts https://github.com/corona-warn-app/cwa-app-ios/pull/4021.

**Comment by KathrinLuecke** [comment]
I think https://github.com/corona-warn-app/cwa-app-ios/pull/4021 shouldn't have been implemented at all, because the texts on this warning screen ("Rote Kachel") was closely aligned and thouroughly discussed with the RKI. We shouldn't make any changes to it without aligning it with the RKI.

**Review by KathrinLuecke — APPROVED** [review]
UA approved

**Comment by Ein-Tim** [comment]
@KathrinLuecke 

> We shouldn't make any changes to it without aligning it with the RKI.

Sorry, I did not know this! Thanks for letting me know.

**Pull request merged**
