### PR TITLE
Capitalize Adjectives

### PR DESCRIPTION
**Pull request by Gudi-24**
## Description
There are several other lists (for example App-Informationen: Neue Funktionen, Häufige Fragen, ...) in CWA where adjectives in front of nouns are written in upper case. Only in this list of locations it is different.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
This exact case has already been **declined** ones by @NataliaLemmerth:

https://github.com/corona-warn-app/cwa-app-android/pull/3038#issuecomment-831049896 says: 

> […] We have a convention that these texts stay with small letters. So I will not merge this suggestion. […]

If we change one case, we should change all cases. I recommend that you open a new issue for this @Gudi-24.

Related issues: https://github.com/corona-warn-app/cwa-app-android/issues/3037, https://github.com/corona-warn-app/cwa-wishlist/issues/491, https://github.com/corona-warn-app/cwa-app-ios/issues/2600

Related PRs: https://github.com/corona-warn-app/cwa-app-android/pull/3038, https://github.com/corona-warn-app/cwa-app-ios/issues/2600, https://github.com/corona-warn-app/cwa-app-android/pull/3038

**Comment by Gudi-24** [comment]
Maybe there are more cases with small letters. But I'm pretty sure that it is wrong to use small letters. And, even more important, there are much more cases (lists) with upper case first letters in CWA. 
Rechtliche Hinweise
Technische Hotline
Erhöhtes Risiko
Niedriges Risiko
Bestätigte Neuinfektionen
Warnende Personen

**Comment by Ein-Tim** [comment]
@NataliaLemmerth 

Could you maybe reconsider this? 

@Gudi-24 I suggest to open an issue in https://github.com/corona-warn-app/cwa-documentation, this makes it easier to keep track.

@dsarkar FYI

**Comment by Ein-Tim** [comment]
I recommend to apply the `on hold` label here.

**Comment by NataliaLemmerth** [comment]
@Gudi-24 Thanks for your suggestion to capitalize adjectives. @DerVogel2020 has rightly proposed the changes. And the proposal had to be declined because of the existing UA guidelines. @Ein-Tim We'll look at it again! It's important to identify all the places where the adjectives are not capitalized in enumerations in case we're going to change it. 

@DerVogel2020 @Ein-Tim @Gudi-24  Thank you very much for contributing to the quality and consistency of the app!

**Review by NataliaLemmerth — APPROVED** [review]
UA approved

**Review by marcussc — APPROVED** [review]

**Review by pascal-brause — APPROVED** [review]

**Pull request merged**
