### PR TITLE
Adjust info screen for release 2.26

### PR DESCRIPTION
**Pull request by naveeddotio**
## Description
Adjust info screen for release 2.26

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13714

## Screenshots
Simulator Screen Shot - Clone 1 of iPhone 11 - 2022-08-03 at 10 58 30

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@CV113 & @naveeddotio 

May I suggest to not show the "Neue Funktionen" screen when first starting the app after the update if there are no new features? I suggest to only have this information under "App-Informationen", but not as a splash screen on app startup.

**Comment by naveeddotio** [comment]
> @CV113 & @naveeddotio
> 
> May I suggest to not show the "Neue Funktionen" screen when first starting the app after the update if there are no new features? I suggest to only have this information under "App-Informationen", but not as a splash screen on app startup.

Thanks for the suggestion but it's POs decision to go like this.

**Comment by Ein-Tim** [comment]
@naveeddotio Ok, I will still open an issue in the https://github.com/corona-warn-app/cwa-wishlist repo.

**Review by 30mar — APPROVED** [review]

**Review by puneetmahali1 — APPROVED** [review]

**Review by CV113 — APPROVED** [review]
UA approved

**Pull request merged**
