### PR TITLE
fix(localization): ExposureSubmissionError_NoRegistrationToken

### PR DESCRIPTION
**Pull request by svewag**
use "Registrierungs-Token" instead of "Registrations-Token"

### CODE REVIEW

**Review by ChristianKienle — APPROVED** [review]

**Review by ChristianKienle — CHANGES_REQUESTED** [review]
Revoking my previous review... should this go into master?

**Comment by haosap** [comment]
Hi @steins-code ,
Any text changes should be aligned with translator?

**Comment by haosap** [comment]
> Revoking my previous review... should this go into master?

I think any text changes should be aligned with translator: https://github.com/corona-warn-app/cwa-app-ios/issues/440

**Comment by inf2381** [comment]
As simple as this PR is, we have to close it unfortunately and mention it in #440

**Pull request closed without merging**
