### PR TITLE
Use completion handler in functions of MockExposureManager (closes #1918)

### LINKED ISSUE #1918: ENACommunity build: MockExposureManager seems broken, does not call its completion handler
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: XCode Simulator (for iPhone 8)
- iOS Version: XCode Simulator (for iOS 14.3)
- App Version: at tag: v1.11.0

## Describe the bug

I have checked-out the cwa-app-ios code at tag "v1.11.0", compiled it for ENACommunity, and now run it on a XCode Simulator for iPhone 8 / iOS 14.3.
I am watching the screen of the simulation and the debug messages, and see the following:

1) Risk check is not successfull, the procedure times out after 8 minutes. I have started debugging. Download of hourly and daily packages is reported successfull, then it calls MockExposureManager.detectExposures, but it seems the mock never calls the completion.

~~2) When I single-step / setup many breakpoints, and the timeout happens before the mock even starts to detect exposures; in this case the timeout does not prevent the mock from starting, and the check continues forever (well, till I brute-force stop it).~~
~~On a first glance it looks like the timeout handling has a race condition in this case (but maybe this is intended, and the timeout shall cover only download from the server?)~~  => moved this part to separate ticket #1941

## Steps to reproduce the issue (1)

* Checkout code at tag "v1.11.0"
* compile for ENACommunity
* setup breakpoints as follows:
  * (a) MockExposureManager line 63 (func detectExposures)
  * (b) ExposureDetectionExecutor line 74 (the completion handler)
  * (c) RiskProvider line 169 (the timeout handler)
* run the simulation and watch breakpoints:
  * hit breakpoint (a) at MockExposureManager.detectExposures
  * continue execution
  * see simulation screen with message "Check is running ..."
  * wait 8 minutes
  * hit breakpoint (c) at timeout handler
  * continue execution
  * see simulation screen with message "Exposure check failed"

Note: breakpoint (b) never triggers.

## Expected behaviour

The mock should call its completion handler.

Note: I have split the ticket and moved the following part to #1941

~~## Steps to reproduce the issue (2)~~
~~* as above: checkout code at tag "v1.11.0" and compile for ENACommunity~~
~~* setup breakpoints (a), (b), (c) as above, plus:~~
~~ * (d) RiskProvider line 188 (during package download)~~
~~* run the simulation and watch breakpoints:~~
~~* hit breakpoint (d) during package download~~
~~* wait more than 8 minutes at the breakpoint, then continue execution~~
~~* hit breakpoint (c) at timeout handler~~
~~* continue execution~~
~~* hit breakpoint (a) at MockExposureManager.detectExposures~~
~~* continue execution~~
~~* see simulation screen with message "Check is running ..."~~
~~* wait forever~~

~~Note: breakpoint (b) never triggers.~~
~~## Expected behaviour~~
~~Either the mock execution should be covered by the overall timeout, or setup its own timeout.~~

## Additional context

I am aware that the ENACommunity build and the mock have not the highest priorities.
Still I can volunteer to look deeper into this, but first would like to know:
* is my expectation wrong / misunderstanding on my side?
* is this already analysed / improved / fixed (and I should avoid duplicate effort)?

---
Internal tracking ID: [EXPOSUREAPP-5006](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5006)

### PR DESCRIPTION
**Pull request by ndegendogo**
This fixes the risk detection behaviour of MockExposureManager in the ENACommunity build for ENF v2.
See github ticket cwa-app-ios/issues/1918.

## Description

The mock now simulates a successfull risk detection. The result of the detection is hard-coded as no detected exposure windows.

I have tested it on the XCode simulator for iOS 14.4. Each of the three added completion handlers was called, I verified this with a manual test and breakpoints.
I have performed no testing on a true device.

## Link to Jira

EXPOSUREAPP-5006

### CODE REVIEW

**Comment by dsarkar** [comment]
@ndegendogo Thanks! Will be forwarded to the ticket and devs will be pinged!

**Comment by ndegendogo** [comment]
> @ndegendogo Thanks! Will be forwarded to the ticket and devs will be pinged!

@dsarkar actually, the CI pipeline seems unhappy - how am I now supposed to continue? Are there any log files or similar so I can figure out what is missing?

**Comment by Ein-Tim** [comment]
@ndegendogo 

This is the failing test (idk if this helps 😁):

https://circleci.com/api/v1.1/project/github/corona-warn-app/cwa-app-ios/24840/output/104/0?file=true&allocation-id=60217673a283782ce790e2c9-0-build%2F5D9B1AFE

Link to circleci: https://app.circleci.com/pipelines/github/corona-warn-app/cwa-app-ios/10199/workflows/da74c782-173b-4b7e-bfcd-0448302ac01a/jobs/24840

**Review by marcussc — APPROVED** [review]

**Comment by marcussc** [comment]
LGTM, thanks for your contribution 👍

**Review by ArturFriesen — APPROVED** [review]
Nice! Thanks!

**Review by whiskey — APPROVED** [review]

**Pull request merged**
