### PR TITLE
Switch to Xcode 12.5

### PR DESCRIPTION
**Pull request by marcussc**
## Description
This updates CircleCI to Xcode 12.5

### CODE REVIEW

**Review by nickguendling — APPROVED** [review]
🙏

**Review by ArturFriesen — APPROVED** [review]
🕺

**Comment by KaiTeuber** [comment]
🥳

**Review by KaiTeuber — APPROVED** [review]

**Review by pascal-brause — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Shouldn't this go into `release/2.9.x` now? 
Version 2.8 has been released today.

**Comment by marcussc** [comment]
@Ein-Tim yeah you are right, but currently the biggest Problem is to get the Unit-Tests green on the CI. TBH I am a little lost why this is failing, since it is running smoothly locally.

**Pull request closed without merging**
