### PR TITLE
Translation Delivery

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them,  @C5311946 @D028372

**Comment by marcussc** [comment]
As requested closing this PR

**Comment by Ein-Tim** [comment]
This would have solved #1877. Will there be a new PR fixing this @marcussc?

**Comment by marcussc** [comment]
> This would have solved #1877. Will there be a new PR fixing this @marcussc?

@Ein-Tim Yeah our Translation Team is on it 👍

**Pull request closed without merging**
