### PR TITLE
Remove 3rd Bullet Point from "Check Validity" screen (Addresses cwa-documentation issue 721) (COMMUNITY)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR removes the 3rd Bullet Point from the "Check Validity" screen & the result screens, as it is out of date.

## Link to Jira
- GitHub Issue: https://github.com/corona-warn-app/cwa-documentation/issues/721
	- Internal Tracking ID: [EXPOSUREAPP-10566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10566)

## Additional Information
Please let me know 
a) If I should do this for all language files
b) If this change is OK for you. I'm still in the Swift learning phase, so please bear with me (-:
c) If I should change the numbers of the bullet points which are still there, I did not change it now because I wanted to avoid any confusion with the translation team

---
Internal Tracking ID: [EXPOSUREAPP-10566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10566)

### CODE REVIEW

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for proving a PR. PR forwarded into Internal Tracking ID: [EXPOSUREAPP-10566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10566)

**Review by KathrinLuecke — APPROVED** [review]
UA approved

**Review by naveeddotio — APPROVED** [review]

**Comment by Ein-Tim** [comment]
This can't go into 2.14 now, or am I wrong?

**Comment by davidlindercwa** [comment]
I've verified that this bullet point indeed can be removed, so please go ahead with the merge of this PR. Thanks for the help!

**Comment by Ein-Tim** [comment]
Awaiting feedback on which branch to target.

**Review by naveeddotio — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@naveeddotio 

You merged this PR into `release/2.14.x`, after version 2.14.1 was already released in the App Store. 
Will this change
a) be included in an upcoming hot fix release (version 2.14.2) or
b) be included in the next minor release (version 2.15.x)?

Thanks for your answer!
Tim

**Comment by Ein-Tim** [comment]
Btw @marcussc this PR is missing the respective milestone. Could you take a look at this, please?

**Pull request merged**
