### PR TITLE
Improve wording of Trace Location info screen (COMMUNITY) (Closes #2342)

### LINKED ISSUE #2342: Strange Wording in Trace Location Info screen
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: -
- iOS Version: -
- App Version: 2.0 RC 1

## Describe the bug

`TraceLocation_Information_Item_RenewQRCode` says:
https://github.com/corona-warn-app/cwa-app-ios/blob/f531dac46eab9f34dc5c8aaf379a5a73eaa15a53/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2216

This sounds strange, the "außerhalb der Öffnungszeiten" shouldn't be on the end of the sentence.

## Steps to reproduce the issue

1. Open CWA version 2.0
2. Scroll to "Sie planen eine Veranstaltung?
3. Click on "QR-Code erstellen"
4. If there's no pop up with the information click on the 3 dots in the right corner and choose "Info"
5. Scroll down and see the last point above of the "Datenschutz und Datensicherheit" box

<details>
<summary>Screenshot</summary>

Current Light Mode

</details>

## Expected behaviour

String should be:
"Wenn Sie dauerhaft einen QR-Code verwenden, sollten Sie diesen einmal täglich außerhalb der Öffnungszeiten neu erstellen."

## Possible Fix

Change the localizable strings.

## Additional context

I'll provide a PR for this.

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR corrects a strange sounding sentence in the "TraceLocation_Information_Item_RenewQRCode" string.

## Link to Jira
non (yet)

## Screenshots

Closes #2342

### CODE REVIEW

**Review by marcussc — APPROVED** [review]

**Comment by janetback** [comment]
Hi @Ein-Tim , the current version is grammatically correct, but I am ok with going with your variant.

**Review by janetback — APPROVED** [review]
UA reviewed.

**Review by tcfos — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Thank you @janetback! 

I know that the gramma is correct, but IHMO that sounded strange. Will you mirror this change into the internal translation system to get this change to Android too? 

Thank you!

**Comment by janetback** [comment]
Hi @Ein-Tim, yes I will make the change for Android too :-). Translation is automatically triggered once the PRs are merged.

**Pull request merged**
