### PR TITLE
Improve wording of certificate QR code scanner (Community)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR improves the wording of "HealthCertificate_QRScanner_instruction".

## Link to Jira
n/a

## Screenshots

| Before | Afterwards |
|---|---|
|  |  |

### CODE REVIEW

**Review by NataliaLemmerth — APPROVED** [review]
UA approved.

**Review by KaiTeuber — APPROVED** [review]

**Comment by nickguendling** [comment]
The milestone is 2.6 but this PR goes against 2.7, did you want to get it in 2.6 instead? I think we could still get it into the 2.6 release if you branch off of 2.6 instead of 2.7

**Comment by Ein-Tim** [comment]
@nickguendling 

I intended to merge into `release/2.7.x` but if there's a way to get this into `release/2.6.x` that would be great! I'll change the branch.

**Comment by Ein-Tim** [comment]
@nickguendling 

New PR: #3197

I failed to rebase this PR, I'm still a newbie with Git, sorry 😅

**Pull request closed without merging**
