### PR TITLE
fix: do not add cell selection for step cells

### LINKED ISSUE #2700: [UX] Step cells should not be selectable
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 Pro
- iOS version: 14.6
- App version: 2.2.1

## Describe the bug

There is a commonly used item template for displaying "steps", e.g. in the submission test result view, submission hotline and submission success view. Currently, when tapping on one of the cells, a selection indicator is displayed, which looks odd to non-technical users knowing that a `UITableView` is behind it:

## Steps to reproduce the issue

1. Add a sample antigen test
2. Tap on the test
3. Scroll down to the "Info" section+
4. Tap on one of the steps

## Expected behaviour

No selection is displayed.

## Possible Fix

Disable cell selection for step cells (fixed in https://github.com/corona-warn-app/cwa-app-ios/pull/2701)

---
Internal Tracking ID: [EXPOSUREAPP-7296](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7296)

### PR DESCRIPTION
**Pull request by hansemannn**
## Description
Fixes https://github.com/corona-warn-app/cwa-app-ios/issues/2700 

---
Internal Tracking ID: [EXPOSUREAPP-7296](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7296)

### CODE REVIEW

**Comment by dsarkar** [comment]
@hansemannn Thanks. Internal Tracking ID: [EXPOSUREAPP-7296](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7296)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Maybe it would make sense to include the cases mentioned in #2245 here too?

**Comment by hansemannn** [comment]
@Ein-Tim Good catch! I'll add those cases, then it should be fine.

**Review by naveeddotio — APPROVED** [review]

**Review by KaiTeuber — APPROVED** [review]

**Comment by hansemannn** [comment]
Hi everyone! We should be all-set here. Thanks for the review!

**Review by marcussc — APPROVED** [review]

**Pull request merged**
