### PR TITLE
Feature/10760 2 g plus check in/10877 adapt certificate priority part 2

### PR DESCRIPTION
**Pull request by nickguendling**
## Description
Unforeseen second part of prioritization changes.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Why the change back to 48h for RATs? 

https://www.zusammengegencorona.de/testen/schnelltest/ clearly states:
"Über das Ergebnis erhält man in der Regel innerhalb von 15 - 30 Minuten einen Nachweis, **der maximal 24 Stunden gültig ist.**"

See also the related discussion in https://github.com/corona-warn-app/cwa-documentation/issues/768.

**Comment by naveeddotio** [comment]
> Why the change back to 48h for RATs?
> 
> https://www.zusammengegencorona.de/testen/schnelltest/ clearly states: "Über das Ergebnis erhält man in der Regel innerhalb von 15 - 30 Minuten einen Nachweis, **der maximal 24 Stunden gültig ist.**"
> 
> See also the related discussion in [corona-warn-app/cwa-documentation#768](https://github.com/corona-warn-app/cwa-documentation/issues/768).

@mlenkeit

**Comment by mlenkeit** [comment]
> Why the change back to 48h for RATs?
> 
> https://www.zusammengegencorona.de/testen/schnelltest/ clearly states: "Über das Ergebnis erhält man in der Regel innerhalb von 15 - 30 Minuten einen Nachweis, **der maximal 24 Stunden gültig ist.**"
> 
> See also the related discussion in [corona-warn-app/cwa-documentation#768](https://github.com/corona-warn-app/cwa-documentation/issues/768).

@Ein-Tim this change aligns the DCC priority logic in CWA with the current DCC business rules for Germany.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Ah yeah, I heard about this and that the DCC business rules are still on 48h. Makes sense for the entry of Germany, but not for inside of Germany.

Okay, anyways, thanks for your clarification!

**Review by KaiTeuber — APPROVED** [review]

**Review by naveeddotio — APPROVED** [review]

**Pull request merged**
