### PR TITLE
[Technical] Fix SwiftLint warnings & configure AnyLint checks

### PR DESCRIPTION
**Pull request by Jeehut**
- [x] Fixes all SwiftLint warnings that were trivially fixable without bigger refactoring (to reduce merge conflicts).
- [x] Configured SwiftFormat as a run-script and ran it to fix many formatting inconsistencies.
- [x] Added some custom Regex based checks using [AnyLint](https://github.com/Flinesoft/AnyLint) (the better SwiftLint custom rules alternative). I've configured a few checks (most of them with autocorrection) and corrected any issues.

You might want to add the `anylint` command to your CI pipeline, but you can also just keep it in the repo to correct some issues manually from time to time if you don't trust the checks yet.

Note: I will not install proprietary software from Microsoft just to ping you about this PR. I think you should improve your workflow in that regard. Also I couldn't find a link to the mentioned Microsoft Teams channel in the README. But this PR is ready for review.

### CODE REVIEW

**Comment by Jeehut** [comment]
@ChristianKienle Why is the CI not running? Do I need to do something? The tests are not working for me locally, but this is also true for the latest development branch, do I need to configure a specific language or something else to get them running?

**Comment by inf2381** [comment]
> @ChristianKienle Why is the CI not running? Do I need to do something? The tests are not working for me locally, but this is also true for the latest development branch, do I need to configure a specific language or something else to get them running?

The CI should build your next commit. Sorry for the inconvenience. I also added a new scheme "ENACommunity" to the project. Please have a look at our latest [README](https://github.com/corona-warn-app/cwa-app-ios#build). 
Did you run the tests using fastlane or what do mean with they don't work locally?

**Comment by Jeehut** [comment]
Thanks @inf2381 for fixing the CI, will try out tonight by rebasing this. Regarding testing, I did not try out fastlane, I just ran tests in the .xcworkspace project via `Cmd+U` like I always do. Maybe it should be more clearly states in the README that tests will only work by running through the fastlane command. Currently it's under the "Build" section which I don't directly assume to be related to testing.

**Comment by inf2381** [comment]
> Thanks @inf2381 for fixing the CI, will try out tonight by rebasing this. Regarding testing, I did not try out fastlane, I just ran tests in the .xcworkspace project via `Cmd+U` like I always do. Maybe it should be more clearly states in the README that tests will only work by running through the fastlane command. Currently it's under the "Build" section which I don't directly assume to be related to testing.

Running the tests in the .xcworkspace project via `Cmd+U` should also work if you select the scheme `ENATests`.

**Comment by Jeehut** [comment]
I just rebased this and fixed several new warnings & issues. I think you should update your CI to make sure that at least `swiftformat .` is being run and no changes are happening by that. Also, I'm in favor of disabling all rules that are not really fixed (like `todo` and `file_length` etc.) and enabling the `--strict` mode of SwiftLint on the CI (`swiftlitn --strict`). This will prevent warnings to reappear all the time. And as I have already mentioned above, you might want to consider to add `anylint` to the CI as well.

@inf2381 Choosing the `ENATests` scheme didn't change anything, still not passing. I've also tried setting German & Germany to the simulator, still not passing. Could it be that it's required to run the backend server locally to get them to pass?

See the screenshot attached:
Bildschirmfoto 2020-06-02 um 18 45 02

When I run via `fastlane test` then it's failing, too. Looks like it's retrying to connect to the simulator for UI tests again and again without success. I have the latest fastlane and xcov installed (just reinstalled them):

```bash
[18:59:58]: ▸ Selected tests
[18:59:58]: ▸ Test Suite ENATests.xctest started
[18:59:58]: ▸ ENStateTests
[19:00:08]: ▸ 2020-06-02 19:00:08.791 xcodebuild[2354:765997]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[19:00:08]: ▸ /Users/Cihat/Library/Developer/Xcode/DerivedData/ENA-fovhavosztpuergceezwbepxqojh/Logs/Test/Run-ENATests-2020.06.02_18-58-49-+0200.xcresult/Staging/2_Test/Diagnostics/ENATests-8E9C2585-358E-4576-B083-E88EB3DDAEB4/ENATests-5841D625-64C7-4703-8344-35A41DBC0DB0/Session-ENATests-2020-06-02_190008-nf3isi.log
[19:00:08]: ▸ 2020-06-02 19:00:08.791 xcodebuild[2354:758912] [MT] IDETestOperationsObserverDebug: (17E83ECC-D5F3-4F5A-BF70-297777F6132A) Beginning test session ENATests-17E83ECC-D5F3-4F5A-BF70-297777F6132A at 2020-06-02 19:00:08.792 with Xcode 11E608c on target <DVTiPhoneSimulator: 0x7fd904dc8d70> {
[19:00:08]: ▸ 		SimDevice: iPhone 11 (FDCAFBEC-26B8-47B9-8002-24009474D349, iOS 13.5, Booted)
[19:00:08]: ▸ } (13.5 (17F61))
[19:00:08]: ▸ 2020-06-02 19:00:08.794 xcodebuild[2354:758912] [MT] IDETestOperationsObserverDebug: (17E83ECC-D5F3-4F5A-BF70-297777F6132A) Finished requesting crash reports. Continuing with testing.
[19:00:09]: ▸ Selected tests
[19:00:09]: ▸ Test Suite ENATests.xctest started
[19:00:09]: ▸ ENStateTests
[19:00:20]: ▸ 2020-06-02 19:00:20.753 xcodebuild[2354:767006]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[19:00:20]: ▸ /Users/Cihat/Library/Developer/Xcode/DerivedData/ENA-fovhavosztpuergceezwbepxqojh/Logs/Test/Run-ENATests-2020.06.02_18-58-49-+0200.xcresult/Staging/2_Test/Diagnostics/ENATests-8E9C2585-358E-4576-B083-E88EB3DDAEB4/ENATests-5841D625-64C7-4703-8344-35A41DBC0DB0/Session-ENATests-2020-06-02_190020-7NLmxN.log
[19:00:20]: ▸ 2020-06-02 19:00:20.753 xcodebuild[2354:758912] [MT] IDETestOperationsObserverDebug: (AE0A6123-2EF9-432C-AF8C-ACCF70F20EBE) Beginning test session ENATests-AE0A6123-2EF9-432C-AF8C-ACCF70F20EBE at 2020-06-02 19:00:20.753 with Xcode 11E608c on target <DVTiPhoneSimulator: 0x7fd904dc8d70> {
[19:00:20]: ▸ 		SimDevice: iPhone 11 (FDCAFBEC-26B8-47B9-8002-24009474D349, iOS 13.5, Booted)
[19:00:20]: ▸ } (13.5 (17F61))
[19:00:20]: ▸ 2020-06-02 19:00:20.756 xcodebuild[2354:758912] [MT] IDETestOperationsObserverDebug: (AE0A6123-2EF9-432C-AF8C-ACCF70F20EBE) Finished requesting crash reports. Continuing with testing.
```

And then I get this (like on the CI):

```bash
Failing tests:
	ENATests:
		ENStateTests.testDisableTracing()
		ENStateTests.testDisableTracingAndBluetoothOff()
		ENStateTests.testDisableTracingAndBluetoothOffAndInternetOff()
		ENStateTests.testDisableTracingAndBluetoothOnAndInternetOn()
		ENStateTests.testEnableTracingStepByStep()
		ENStateTests.testInitialState()
		ENStateTests.testRestrictedState()
		ENStateTests.testTurnOffBluetooth()
		ENStateTests.testTurnOffTurnOnInternet()
		ENStateTests.testUnknownState()

** TEST FAILED **
[19:01:03]: Exit status: 65
+--------------------+----+
|      Test Results       |
+--------------------+----+
| Number of tests    | 77 |
| Number of failures | 0  |
+--------------------+----+
```

CI also seems to fail although no tests are failing ... weird one.

**Comment by Jeehut** [comment]
Ok, found and fixed the issue via 896cb42c91fef7520d0b0ccb43898a3cd06ba51a. Tests should pass now (at least they are now on my machine)! 🎉

**Comment by inf2381** [comment]
I think your PR changes too many files and thus, you are getting merge conflicts all the time. I would recommend to create one pull request per rule you want to fix. For instance one PR for all force_unwrapping violations.

**Comment by Jeehut** [comment]
@inf2381 Sure, I can do that, or I just rebase again and you have a look if you have the time now? Also, what's your thoughts behind adding the `--strict` mode for SwiftLint to the CI so no new warnings arise? Then I could fix all the warnings in one go.

**Comment by Jeehut** [comment]
Okay since you're not answering for so long I assume doing quick actions here is not feasible. I will split this into many small PRs then, thanks for the consideration!

**Comment by tkowark** [comment]
Dear @Jeehut , thanks for all your work on this. Just as a heads up: the team is currently working tirelessly on implementing features from the backlog and will also not be able to respond to new PRs on short notice. To spare you some extra work of constantly rebasing, maybe you could wait until the team opens a dedicated issue for the linting error fixes?

Thanks for your understanding

**Comment by Jeehut** [comment]
@tkowark Thank you for the heads up, then I will just wait a few days and do the splitting up into smaller tasks and fixing issues sometime next week (if the warnings are not already gone by then).

**Comment by inf2381** [comment]
> @tkowark Thank you for the heads up, then I will just wait a few days and do the splitting up into smaller tasks and fixing issues sometime next week (if the warnings are not already gone by then).

@Jeehut We released our beta this night and are now open again for improvements / fixed warnings. As we requested smaller PRs especially for SwiftLint warnings, I will close this PR now. I'm looking forward to your contributions.

**Comment by Jeehut** [comment]
@inf2381 Thanks for the info, I will take some tome tonight or tomorrow to fix lint warnings in as small as possible PRs. Stay tuned ...

**Comment by Jeehut** [comment]
@tkowark @inf2381 I just posted the first 6 PRs to bring the SwiftLint side of the warnings down to 0 in these PRs: https://github.com/corona-warn-app/cwa-app-ios/pull/516, https://github.com/corona-warn-app/cwa-app-ios/pull/518, https://github.com/corona-warn-app/cwa-app-ios/pull/522, https://github.com/corona-warn-app/cwa-app-ios/pull/527, https://github.com/corona-warn-app/cwa-app-ios/pull/531, https://github.com/corona-warn-app/cwa-app-ios/pull/534.

I'm waiting now for your feedback before continuing to work on improved linting (both adding more rules & configurations, but also adding new linters & custom rules to help keep the code base clean). Thank you in advance for considering my changes!

**Pull request closed without merging**
