### PR TITLE
Improve 2G+ with RAT text

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR updates "HealthCertifiedPerson_AdmissionState_description2GPlusAntigen" so that it's clearer that the certificates fulfill 2G+ rules, but if a PCR test is required. This is done to avoid confusion ("My CWA showed that my certificates fulfill 2G+ requirements, while actually they didn't!").

## Link to Jira
Non.

## Screenshots
Not possible, sorry. 

## Additional information

Please make sure that the logic is correct (that this text is not shown if a PCR & a RAT certificate is stored in the app).

### CODE REVIEW

**Review by CV113 — APPROVED** [review]
UA approved

**Comment by Ein-Tim** [comment]
https://github.com/corona-warn-app/cwa-app-ios/commit/3be32259878409c1959e063953dfab36f43908ad added a missing ",".

**Review by pascal-brause — APPROVED** [review]

**Comment by naveeddotio** [comment]
@Ein-Tim The text needs to be updated in testTwoGPlusAntigen() unit test too.

**Review by naveeddotio — CHANGES_REQUESTED** [review]
Please fix testTwoGPlusAntigen()

**Comment by Ein-Tim** [comment]
I will take a look @naveeddotio. Thanks.

**Comment by Ein-Tim** [comment]
@naveeddotio Fixed with [`c396668`](https://github.com/corona-warn-app/cwa-app-ios/pull/4026/commits/c396668530821a2a18a81caf5ac8ebd2c721af89).

Please take another look.

**Review by naveeddotio — APPROVED** [review]

**Pull request merged**
