### PR TITLE
COMMUNITY: Remove outdated sentence reg. free test to be prepared for end of free RATs ("Bürgertests")

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR removes an outdated sentence reg. the legal entitlement to a free test if the CWA shows an increased risk encounter.

I already provided this change via https://github.com/corona-warn-app/cwa-app-ios/pull/4391 however, this PR was closed with the comment that there is a general overhaul of this screen planned soon. However, this was more than 3 months ago and there was no overhaul of this screen.

As reported by [tagesschau.de](https://www.tagesschau.de/inland/coronavirus-buergertest-101.html), the federal minister of health today announced that there won't be any free rapid antigen tests for everyone anymore after 31.06.22.

To be prepared for this change, I'm providing this PR which removes the sentence reg. the entitlement to free rapid antigen tests. 

## Related Links to JIRA & GitHub
- GitHub Issue https://github.com/corona-warn-app/cwa-documentation/issues/877
	- JIRA link: Internal Tracking ID: [EXPOSUREAPP-13209](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13209) 

## Screenshots
| Dark mode | Light mode |
|---|---|
|  |  |

### CODE REVIEW

**Comment by KathrinLuecke** [comment]
Hi @Ein-Tim,
we need to discuss this internally and align with the RKI about the exact wording of this section.
Therefore I cannot approve this PR at the moment.
Best regards,
Kathrin

**Comment by Ein-Tim** [comment]
@KathrinLuecke Okay, but please leave this PR open and discuss with the RKI ASAP, maybe also suggest to first remove the sentence completely and then think about a better solution. 

My main intention is to make sure that no wrong statement ist in the app when the new regulations goes into effect.

**Comment by Ein-Tim** [comment]
Base branched changed to `release/2.25.x` from `release/2.24.x`.

Is there any update you can share with us @KathrinLuecke?

**Comment by Ein-Tim** [comment]
Closing in favour of https://github.com/corona-warn-app/cwa-app-ios/pull/4651.

**Pull request closed without merging**
