### PR TITLE
Replace entfernen by löschen

### PR DESCRIPTION
**Pull request by CV113**
Replace entfernen by löschen

### CODE REVIEW

**Review by marcussc — APPROVED** [review]

**Review by KathrinLuecke — COMMENTED** [review]
@CV113 Is it ok to also change the legal strings? I thought we were not supposed to change them?

**Comment by CV113** [comment]
> @CV113 Is it ok to also change the legal strings? I thought we were not supposed to change them?

oh, I'm not sure- I thought it was aligned with all colleagues (even with the colleagues of the legal department) to replace entfernen by löschen. Let me ask and I will come back to you asap

**Review by naveeddotio — CHANGES_REQUESTED** [review]
Legal text has to be approved by the lawyers. Please take Martin Hermes into the loop before changing anything even one word.

**Review by KathrinLuecke — APPROVED** [review]
UA approved

**Review by naveeddotio — APPROVED** [review]
@CV113 Checked with Martin and it's okay to change the texts.

**Pull request merged**
