### PR TITLE
[Feature] risk cell ui polish

### PR DESCRIPTION
**Pull request by aleksandr-tikhonov**
This PR updates ui staff some of cell on home screen. including adapt `ENALabel` and `ENAButton`

### CODE REVIEW

**Review by eisvogel — COMMENTED** [review]
Looks good, however, something seems to be wrong:
image

**Review by johannesrohwer — APPROVED** [review]

**Comment by aleksandr-tikhonov** [comment]
> Looks good, however, something seems to be wrong:
> image

Hi @EisvogelSAP, do you mean "Aktualisiert:  - " ?

**Comment by EisvogelSAP** [comment]
Nope, why is it red although it is showing no contacts?

**Comment by aleksandr-tikhonov** [comment]
> Nope, why is it red although it is showing no contacts?

this text depends on `numberRiskContacts` if it's less 1 it has such title.

**Comment by EisvogelSAP** [comment]
Yes, but why is showing high risk then? When there are not contacts the risk should be low.

**Comment by aleksandr-tikhonov** [comment]
> Yes, but why is showing high risk then? When there are not contacts the risk should be low.

there was debug code, I deleted it

**Review by eisvogel — APPROVED** [review]

**Pull request merged**
