### PR TITLE
Add year and copyright holder to MIT license (Fixes #2413) (COMMUNITY)

### LINKED ISSUE #2413: [CWA-Docu] MIT License is not customised
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

## Describe the bug

The mit license is not customised. (Year and contributors are only placeholders)

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-6343](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6343)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR adds missing information to the MIT license file.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6343

---

**Closes #2413**

### CODE REVIEW

**Comment by dsarkar** [comment]
@Ein-Tim, regarding this issue: "... Adding RKI or SAP as copyright holder would be wrong as the MIT license is only for the external copyright holders of copied and integrated source code." 

This file is a template being used by another tool.

**Comment by Ein-Tim** [comment]
@dsarkar 

Oh, okay. So the external tool which is licensed under the MIT license and they forgot to put these fields in?

Which tool exactly is this? Maybe they have meanwhile fixed this?

**Comment by dsarkar** [comment]
@Ein-Tim FYI https://github.com/corona-warn-app/cwa-app-ios/pull/1504

**Comment by Ein-Tim** [comment]
@dsarkar 

Okay, understood.

Closing this PR.

**Pull request closed without merging**
