### PR TITLE
Write QR code consistently (Addresses #3792)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR writes QR code consistently with a lowercase c.

## Link to Jira
- GitHub Issue #3792 
	- [EXPOSUREAPP-11165](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11165)

### CODE REVIEW

**Comment by marcussc** [comment]
Hey @Ein-Tim, we would have to fix this in our translation tool, otherwise your changes would be overwritten on the next translation delivery. I am in contact with our translation team to make them aware of your proposed changes.

**Comment by Ein-Tim** [comment]
@marcussc Ah yes, I completely forgot! If it's easier for you, I can close this PR and the change is done by @service-tip-git with the next translation update.

**Comment by marcussc** [comment]
@Ein-Tim yeah I think its the best way. :)
Happy Easter ;)

**Comment by Ein-Tim** [comment]
@marcussc 

Okay, closing! Thanks & same back to you!

**Pull request closed without merging**
