### PR TITLE
fix/7302 share button not working

### PR DESCRIPTION
**Pull request by naveeddotio**
## Description
Changed the order of the views

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7032

## Screenshots
Simulator Screen Shot - iPhone 12 - 2021-05-06 at 14 33 24

### CODE REVIEW

**Review by 30mar — APPROVED** [review]

**Review by whiskey — COMMENTED** [review]
Do you have capacity for a UI test here? If not ping me.

**Review by pascal-brause — APPROVED** [review]
Indeed with @whiskey, a UITest would be nice

**Comment by marcussc** [comment]
Disabeling auto merge, currently ongoing discussion if it should go to 2.2 already

**Comment by marcussc** [comment]
Replaced by: https://github.com/corona-warn-app/cwa-app-ios/pull/2646

**Pull request closed without merging**
