### PR TITLE
Update Localizable.legal.strings

### PR DESCRIPTION
**Pull request by KathrinLuecke**
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14378

### CODE REVIEW

**Review by puneetmahali1 — APPROVED** [review]
👍

**Review by naveeddotio — APPROVED** [review]

**Review by naveeddotio — CHANGES_REQUESTED** [review]
Should also be done with Turkish language manually

**Comment by KathrinLuecke** [comment]
@naveeddotio Yes, I'm going to do this.

**Comment by naveeddotio** [comment]
> @naveeddotio Yes, I'm going to do this.

@KathrinLuecke Please update the same PR

**Pull request closed without merging**
