### PR TITLE
Add all unit tests to SmokeTests testplan.

### PR DESCRIPTION
**Pull request by ArturFriesen**
## Description
This PR changes the SmokeTests testplan to include all unit tests.

### CODE REVIEW

**Review by tcfos — APPROVED** [review]

**Comment by marcussc** [comment]
Not sure if this clashes with: https://github.com/corona-warn-app/cwa-app-ios/pull/1402 
@whiskey  ?

**Comment by whiskey** [comment]
@marcussc Should not as I'm not actively using the Smoke Testplan. However, does 'all tests' mean 'all unit tests' – @ArturFriesen?

**Review by whiskey — APPROVED** [review]
Just had that question above. Else I'm ok with this 👍

**Comment by ArturFriesen** [comment]
> @marcussc Should not as I'm not actively using the Smoke Testplan. However, does 'all tests' mean 'all unit tests' – @ArturFriesen?

Yes. It means all unit tests.

**Pull request merged**
