### PR TITLE
Story/11608 fault tolerant name handling/storybranch

### PR DESCRIPTION
**Pull request by pascal-brause**
## Description
PR for merging the story branch into the release branch.
This story brings a more tolerant naming matching pattern to health certificates and their persons.
This applies at startup (new migration), also when adding or removing one certificate.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11608

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Is there some note shown for the user when certificates are merged after updating to version 2.19?

If not, this should be considered to avoid confusion (like when the certificates tab was introduced, see https://www.coronawarn.app/en/blog/2021-06-30-cwa-impfnachweis-zertifikatsbereich).

@UA-Team

**Review by naveeddotio — APPROVED** [review]

**Comment by thomasaugsten** [comment]
For 2.19 is no notification for the user planned. 
We will discuss effort and benefit for 2.20.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay, but if you start merging certificates in 1.19, showing a message in 2.20 won't help much, I guess 😅

**Review by nickguendling — CHANGES_REQUESTED** [review]
I was just checking the complete implementation and I think I found a bug in the add case and then the app crashed when I deleted the certificate again

**Comment by pascal-brause** [comment]
> I was just checking the complete implementation and I think I found a bug in the add case and then the app crashed when I deleted the certificate again

Solved by PR https://github.com/corona-warn-app/cwa-app-ios/pull/4243. But anyway blocked until we have a decision about a user information after a successful regrouping.

**Comment by marcussc** [comment]
> > I was just checking the complete implementation and I think I found a bug in the add case and then the app crashed when I deleted the certificate again
> 
> Solved by PR #4243. But anyway blocked until we have a decision about a user information after a successful regrouping.

@pascal-brause 
Can't we merge this already and bring the notification once it's decided?

**Review by nickguendling — APPROVED** [review]

**Pull request merged**
