### PR TITLE
fix typo eingescheckt → eingecheckt

### PR DESCRIPTION
**Pull request by ssp**
## Description
Fixes a typo in the German introduction text for check-ins.

## Link to Jira
n/a

## Screenshots
n/a

### CODE REVIEW

**Review by janetback — APPROVED** [review]
UA approved

**Comment by janetback** [comment]
@ssp - thanks for pointing this out!

**Comment by marcussc** [comment]
Hey @ssp,
thanks for the Contribution. Since this Text is only shown in the Version 2.0 of the App and will be removed with the next version (2.1) it is sadly too late to have this change merged.

**Comment by Ein-Tim** [comment]
@ssp 

Your change was made in #2504

**Pull request closed without merging**
