### PR TITLE
Localization: Use localized "OK" for error alerts

### PR DESCRIPTION
**Pull request by lennartstolz**
The "OK" action of the `alertError` method did use `"OK"` instead of the localized string `AppStrings.Common.alertActionOk`).

This PR shouldn't change anything for now, as both supported languages make use of
 
```
"Alert_ActionOk" = "OK";
```

in their corresponding `Localizable.strings` files.

### CODE REVIEW

**Comment by lennartstolz** [comment]
(I retriggered `circleci`  by a force push .. 🤞 that it doesn't get stuck again).

**Review by SebastianWild — APPROVED** [review]
👍
Not sure why the build job is stuck. Tagging @inf2381

**Comment by lennartstolz** [comment]
Thank you @SebastianWild . Could it be because this branch is based on and targeting the `development` branch (like mentioned in the contribution guidelines) instead of the `next` branch as most PRs do?

**Review by inf2381 — APPROVED** [review]

**Comment by inf2381** [comment]
@lennartstolz It seems like CircleCI wasn't authorized to access your organization.

**Pull request merged**
