### PR TITLE
Chore/8990 mock en manager

### PR DESCRIPTION
**Pull request by ndegendogo**
## Description

This PR implements a mock ENManager for the community build, as proposed at https://github.com/corona-warn-app/cwa-app-ios/issues/3283.
I have not implemented the complete interface of the Apple API, but focussed basically on what cwa actually uses today (protocol Manager).

## Link to Jira

Internal Tracking-ID: EXPOSUREAPP-8990

### CODE REVIEW

**Review by pascal-brause — COMMENTED** [review]
I think the part of the RateLimitLogger was already reviewed, do you have to re-merge the actual 2.9.x branch?

**Comment by ndegendogo** [comment]
> I think the part of the RateLimitLogger was already reviewed
yes, I hope I didn't muddle up that part ....

I started the branch from 2.9.x, after the soft rate limit was merged.
Later I submitted the PR, but meanwhile 2.10 was active ... so I merged 2.10 into my branch ... but RateLimitLogger was not yet on 2.10 at that time ....

Should I better start over with a fresh branch? @pascal-brause

**Review by 30mar — APPROVED** [review]

**Comment by ndegendogo** [comment]
I just merged the newest 2.10 - looks much better now :-)

**Review by pascal-brause — APPROVED** [review]
Sorry - could not response but you solved it well :).

**Pull request merged**
