### PR TITLE
Story/11620 adjust info screen for release 2.19

### PR DESCRIPTION
**Pull request by naveeddotio**
## Description
Adjust info screen for new features in release 2.19

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11621

## Screenshots
Simulator Screen Shot - Clone 2 of iPhone 12 - 2022-03-01 at 13 11 45
Simulator Screen Shot - Clone 2 of iPhone 12 - 2022-03-01 at 13 13 48

### CODE REVIEW

**Review by CV113 — APPROVED** [review]
UA approved

**Review by 30mar — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@CV113 Why is the new feature to select the federal states (see https://github.com/corona-warn-app/cwa-app-ios/pull/4218) not explained in the new features screen?

**Comment by Ein-Tim** [comment]
@KathrinLuecke 

Okay, then the PR #4218 has the wrong milestone assigned to it?

**Comment by Ein-Tim** [comment]
@KathrinLuecke Are you sure? The whole branch was merged into 2.19: https://github.com/corona-warn-app/cwa-app-ios/pull/4257

**Comment by KathrinLuecke** [comment]
The code was developed in 2.19 and is part of it, but it's not active (deactivated through the configuration framework). So the functionality is not visible.

**Comment by Ein-Tim** [comment]
@KathrinLuecke Ah, okay!

**Pull request merged**
