### PR TITLE
Add recommendation to check how old a RAT is allowed to be in your federal state

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
Due to https://github.com/corona-warn-app/cwa-documentation/issues/768, which should definitely be fixed by changing the duration how long a RAT is shown in the app, this PR extends a sentence in "ExposureSubmissionResult_Negative_Antigen_Proof_Desc". It recommends to check the local requirements for a negative RAT reg. how long RATs are valid.

## Link to Jira
[EXPOSUREAPP-10853](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10853)

## Screenshots
Not possible, as I don't have a test which I could add to the simulator. 

---
Internal Tracking ID: [EXPOSUREAPP-10853](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10853)

### CODE REVIEW

**Comment by dsarkar** [comment]
Hi @Ein-Tim There is a typo in your PR.

**Comment by Ein-Tim** [comment]
@dsarkar 

No idea what you mean 😉

Thanks for the note, fixed! 

Could you please mirror https://github.com/corona-warn-app/cwa-documentation/issues/768 to JIRA? I think this is quite a significant issue 😅

Thank you & have a nice Sunday!

**Comment by KathrinLuecke** [comment]
Hello @Ein-Tim , thanks for this PR. There is a change for this text planned anyhow for the next release. The concrete changes are still under discussion, so I don't know if it will include the changes requested by you. I will update this PR when I know more.
Best regards,
Kathrin

**Review by CV113 — APPROVED** [review]
UA approved

**Comment by Ein-Tim** [comment]
@KathrinLuecke 

Okay, thanks for the feedback! I recommend you take https://github.com/corona-warn-app/cwa-documentation/issues/768 into account when you are making changed to this screen.

**Review by pascal-brause — APPROVED** [review]

**Review by naveeddotio — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Obsolete with #3923.

Closing.

**Pull request closed without merging**
