### PR TITLE
Feature/10350 ticketvalidation consent/10542 consent screen

### PR DESCRIPTION
**Pull request by pascal-brause**
## Description
First consent screen for ticket validation.

## Link to Jira
Mainstory: https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10350
Subtask: https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10542

## Screenshots

10542-alert

10542-1-dark
10542-2-dark
10542-3-dark
10542-alert-dark

### CODE REVIEW

**Review by CV113 — APPROVED** [review]
UA approved

**Review by ArturFriesen — APPROVED** [review]

**Comment by vaubaehn** [comment]
Hi @CV113 and @mlenkeit 
I'm not 100% sure, but I think the consent is missing something important:
There may be 3 different parties involved: CWA, vendor and the authorized validation service (public or private). (See: https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_traveller-onlinebooking_en.pdf#%5B%7B%22num%22%3A25%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C62%2C440%2C0%5D)
From the text of the consent, it looks like data is only processed by app (CWA) and vendor.
Could you check whether it's necessary to integrate information about the validation service, too?
Thank you ❤️

**Comment by mlenkeit** [comment]
> I think the consent is missing something important: There may be 3 different parties involved: CWA, vendor and the authorized validation service (public or private). 

@vaubaehn the legal relationships between all involved parties for the Ticket Validation feature have carefully been reviewed by legal experts and were taken into consideration by them when the legal texts were created. 😉

**Comment by vaubaehn** [comment]
@mlenkeit 

> @vaubaehn the legal relationships between all involved parties for the Ticket Validation feature have carefully been reviewed by legal experts and were taken into consideration by them when the legal texts were created. 😉

Thank you for having a look - then I don't want to be more popy than the pope 😁

**Review by KaiTeuber — APPROVED** [review]

**Comment by vaubaehn** [comment]
> Could you check whether it's necessary to integrate information about the validation service, too?

Just realized that my question was a valid one, and that there is additional information regarding the validation service, when getting a seperate consent II to submit data to the validation service.

**Pull request merged**
