### PR TITLE
Prepare Community settings

### PR DESCRIPTION
**Pull request by holtwick**
The community scheme still uses the regular configurations, instead it should use the **Community** configuration. Some settings in this config have been adjusted as well, such the beginner just needs to add the **Development Team** info to get started.

cc @inf2381 
relates to #35 and #43

### CODE REVIEW

**Comment by inf2381** [comment]
Hi @holtwick! Thanks for your efforts. We need this setup for our internal build tool. Could you please adjust adjust your PR to still use the user defined variable in the original schemes and use automatic signing only in the community scheme?

**Comment by holtwick** [comment]
Ops, sorry. Struggling with GtHub ;) Will send a new patch shortly.

**Comment by haosap** [comment]
Hi @holtwick ,
Please have a look at:
image
Please keep the Debug,Release , RelaseToAppStore.

**Comment by holtwick** [comment]
Hi @haosap @inf2381, sorry I messed up the PR, but now it should be fine again. Now it only changes the community scheme.

**Comment by holtwick** [comment]
@inf2381 in my first PR I just changed the community configurations, will that influence your build  process as well? If not it would be great to change those, so we can write a small sum up of how to get started with the community build. 

CleanShot 2020-06-01 at 15 31 52@2x

**Comment by inf2381** [comment]
> @inf2381 in my first PR I just changed the community configurations, will that influence your build process as well? If not it would be great to change those, so we can write a small sum up of how to get started with the community build.
> 
> CleanShot 2020-06-01 at 15 31 52@2x

Looks good as our internal build tool only uses the ENA scheme. I already started to document it [here](https://github.com/corona-warn-app/cwa-app-ios#run). Feel free to add more information there. 😊

**Review by inf2381 — APPROVED** [review]

**Review by ChristianKienle — APPROVED** [review]
LGTM. Thank you very much @holtwick for making it more convenient for the OS community to contribute to this project.

**Pull request merged**
