### PR TITLE
Feature/10313 port request key submission

### PR DESCRIPTION
**Pull request by ArturFriesen**
## Description
Porting the submission request to new http service.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10313

### CODE REVIEW

**Review by KaiTeuber — APPROVED** [review]
👍

**Review by pascal-brause — COMMENTED** [review]
I think you missed to remove `URLRequest.keySubmissionRequest()` and the `submissionURL` in the `HTTPClient+Configuration`?

**Comment by ArturFriesen** [comment]
> I think you missed to remove `URLRequest.keySubmissionRequest()` and the `submissionURL` in the `HTTPClient+Configuration`?

Good catch. I removed it now.

**Review by pascal-brause — APPROVED** [review]
👍

**Pull request merged**
