### PR TITLE
Fix/12215 app information faq link twice

### PR DESCRIPTION
**Pull request by KaiTeuber**
## Description
Remove FAQ link from the app information page because it on home screen's more section already

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12215

## Screenshots
https://user-images.githubusercontent.com/2675578/170706920-3ef1427b-7cdb-46a4-809c-7bb6379a89b1.mp4

### CODE REVIEW

**Review by naveeddotio — APPROVED** [review]

**Review by nickguendling — DISMISSED** [review]
I think this is a sensible suggestion by the tester, but in Figma the link exists in both places. So it should be clarified with UX and Figma should be updated. Otherwise we will get a reverse bug ticket at some point about the missing FAQ link 😄

**Comment by KaiTeuber** [comment]
> I think this is a sensible suggestion by the tester, but in Figma the link exists in both places. So it should be clarified with UX and Figma should be updated. Otherwise we will get a reverse bug ticket at some point about the missing FAQ link 😄

**Comment by KaiTeuber** [comment]
i closed the PR until it's clarified by Anna-Maria

**Review by flxschmidt — APPROVED** [review]
LGTM 👍

**Review by CV113 — APPROVED** [review]
UA approved

**Pull request merged**
