### PR TITLE
fix(settings): properly check cell actions (closes #1458)

### LINKED ISSUE #1458: Tapping on settings cells always open the "Transnational Exposure Logging" information
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When tapping on settings cells, the app always opens the "Translational Exposure Logging" info view, which irritates user when they did not request that information. See the attached video for details! 

## Expected behaviour

The "Translational Exposure Logging" info view should only be shown when tapping on the "Translational Exposure Logging" cell.

## Steps to reproduce the issue

1. Go to settings
2. Click on any of the settings cells

Video of the issue: https://www.dropbox.com/s/orllcgddcfo51qb/CWA_iOS_Settings_Bug_Repro.MP4?dl=0

## Technical details

- iOS Version: 121
- Device: iOS Simulator / iPhone 11 Pro

## Possible Fix

Guard the cell item-type before opening the view. A PR is ready for this: https://github.com/corona-warn-app/cwa-app-ios/pull/1459

Thank you for allowing OSS contributions on this project!

---
Internal Tracking ID: EXPOSUREAPP-3616

### PR DESCRIPTION
**Pull request by hansemannn**
## Checklist

* [x] This PR does not change text that hasn't been signed off with the RKI. Have a look at the pinned issue [440](https://github.com/corona-warn-app/cwa-app-ios/issues)
* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [x] [Link your Pull Request to an issue](https://github.com/corona-warn-app/cwa-app-ios/issues/1458) - Pull Requests that are not linked to an issue with you as an assignee will be closed.
* [x] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)

## Description

When tapping on settings cells, the app always opens the "Translational Exposure Logging" info view, which irritates user when they did not request that information. See the attached video for details! This PR fixes this behavior.

Video of the issue: Video of the issue: https://www.dropbox.com/s/orllcgddcfo51qb/CWA_iOS_Settings_Bug_Repro.MP4?dl=0

### CODE REVIEW

**Comment by hansemannn** [comment]
Please let me know if the branch is fine! In prior contributions, there was a `development` branch bu that seems to be gone. You can also rebase this PR, since external editing is enabled. Thx!

**Review by KaiTeuber — APPROVED** [review]
Thanks, looking good to me.

**Comment by nickguendling** [comment]
Thanks for your contribution! This looks good! 👍

**Review by nickguendling — APPROVED** [review]

**Comment by hansemannn** [comment]
Thanks guys! Happy to help :-)

**Pull request merged**
