### PR TITLE
[Feature] Legal notice screen closes #82

### LINKED ISSUE #82: Show 3rd party libs usage in App Informationen
## Feature description

As an open source project, we also leverage several open source projects from community. These projects should be shown in our app. After aligning with Ux colleagues, the screenshot looks like:

### Screenshot
image

## Actions
- [ ] Create Rechtliche Hinweise on App Informationen
- [ ] Create a static file containing all information from THIRD-PARTY-NOTICES
- [ ] Create the Rechtliche Hinweise Viewcontroller and render the contents as the screenshot showed. (**No storyboard**)

### PR DESCRIPTION
**Pull request by frnkschmtt**
Resolves issue https://github.com/corona-warn-app/cwa-app-ios/issues/82

legal-notice-screen1
legal-notice-screen2
legal-notice-screen3

I adapted the concept of the existing AppInformationHelp with related Model and ModelData files.
Furthermore I integrated the new AppInformationLegalViewController into the existing AppInformation.storyboard. I suggest to tackle the storyboard refactoring in a separate task to keep this PR manageable.

### CODE REVIEW

**Comment by frnkschmtt** [comment]
> Hi @frnkschmtt ,
> Where do you load the text of 3rd party lib?

Hi @haosap, you can find the 3rd party licensing texts in the file AppInformationLegalModelData.swift
Like I mentioned above I adapted the same approach which is already used for AppInformationHelp with a Model and ModelData for static strings. But as of now whenever a new dependency is added we have to maintain both places manually:
- THIRD-PARTY-NOTICES
- AppInformationLegalModelData.swift

I can think of a more generic approach to display the licensing info by reading the content of THIRD-PARTY-NOTICES directly but this requires restructuring this file (e.g. JSON or PList). Going one step further, I can think of adding this (and maybe a license check) step to CI so that each build gets an updated and accurate content for THIRD-PARTY-NOTICES file.

**Comment by inf2381** [comment]
@frnkschmtt could you please resolve the merge conflicts? After merging your pull request, we can integrate it in (feature/polish-app-information)[https://github.com/corona-warn-app/cwa-app-ios/tree/feature/polish-app-information]. Thanks for your efforts!

**Comment by frnkschmtt** [comment]
> @frnkschmtt could you please resolve the merge conflicts? After merging your pull request, we can integrate it in [feature/polish-app-information](https://github.com/corona-warn-app/cwa-app-ios/tree/feature/polish-app-information). Thanks for your efforts!

Done

**Review by inf2381 — APPROVED** [review]

**Comment by inf2381** [comment]
I'm currently fixing the conflicts. Will update soon.

**Review by eisvogel — APPROVED** [review]

**Pull request merged**
