### PR TITLE
[Bug] Update risk level cell on home screen

### PR DESCRIPTION
**Pull request by eisvogel**
This PR re-implements changes which were lost during the "risk calculation era" (shame on you, whoever pressed "resolved with mine").

|Before|After|
|:--|:--|
|image|image|

### CODE REVIEW

**Comment by ChristianKienle** [comment]
😇

**Review by haosap — APPROVED** [review]

**Review by i336616 — APPROVED** [review]
👍

**Review by johannesrohwer — APPROVED** [review]

**Comment by aleksandr-tikhonov** [comment]
chevron icon doesn't change size according to dynamic type
Screenshot 2020-06-12 at 08 58 30

**Review by aleksandr-tikhonov — COMMENTED** [review]
.

**Comment by aleksandr-tikhonov** [comment]
> chevron icon doesn't change size according to dynamic type
> Screenshot 2020-06-12 at 08 58 30


_this is aligned with design, not suppose to change because of the bordered view_

**Review by aleksandr-tikhonov — APPROVED** [review]

**Pull request merged**
