### PR TITLE
UI: Change "Infos" to "Informationen" (COMMUNITY)

### LINKED ISSUE #2543: Rename the Infos Button in Check-in Page
## Current Implementation

Press the 3 dot button, it says Infos instead of Informationen, as it is in the Tagebuch page.

## Suggested Enhancement

Rename to "Informationen"

## Expected Benefits

---
Internal Tracking ID: [EXPOSUREAPP-6853](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6853)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR would fix #2543.
Change "Infos" to "Informationen" in 3 dot menu of the „My Check-Ins“ & „My QR Codes“ screen.

## Link to Jira
non (yet)

## Screenshots

---
Internal Tracking ID: [EXPOSUREAPP-6853](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6853)

### CODE REVIEW

**Comment by DerVogel2020** [comment]
I would prefer the other way: Informationen instead of Infos, since in the android app it's also "Informationen".

**Comment by Ein-Tim** [comment]
@DerVogel2020 
Okay, I'll wait for feedback from the UI/UX team and if they want this change too I'll change it.

**Comment by marcussc** [comment]
@Ein-Tim @DerVogel2020  help me out here. The linked Issue has as solution:

> Suggested Enhancement
> 
> Rename to "Informationen"


But it already is "Informationen".

**Comment by Ein-Tim** [comment]
@marcussc 

@DerVogel2020 wanted to change "Infos" in the 3 dot menus of the "My Check-Ins" & "My QR-Code" to "Informationen". 
Instead I changed the "Informationen" in the contact diary 3 dot menu to "Infos".

**Comment by janetback** [comment]
Hi @Ein-Tim - unless there are restrictions on the amount of space available, I would prefer to leave 'Informationen'
cc @DerVogel2020, @marcussc

**Comment by DerVogel2020** [comment]
I would prefer Informationen, too. See also corona-warn-app/cwa-app-android#2944.

**Comment by Ein-Tim** [comment]
@janetback 

Than we change "Infos" to "Informationen" in the "My Check-Ins" & "My QR-Code" screen, ok?

**Comment by Ein-Tim** [comment]
@janetback Could you take another look? 

I now changed "Infos" to "Informationen".

FYI @DerVogel2020 @marcussc

**Review by DerVogel2020 — APPROVED** [review]

**Review by whiskey — APPROVED** [review]

**Comment by DerVogel2020** [comment]
@whiskey If the label and milestone are necessary, please add them also to the issue/commit for android
https://github.com/corona-warn-app/cwa-app-android/issues/2944
and/or
https://github.com/corona-warn-app/cwa-app-android/commit/b47307c1048f5818ab9a876d31c387eb6551ea20

**Comment by dsarkar** [comment]
@janetback @whiskey @SabineLoss FYI, see Internal Tracking ID: [EXPOSUREAPP-6853](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6853)

**Pull request merged**
